# Generated by Django 5.2.11 on 2026-02-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='full_description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
    ]
