# Generated by Django 5.2.11 on 2026-02-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_alter_post_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='posts/photos/', verbose_name='Первое фото в описании'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='posts/photos/', verbose_name='Второе фото в описании'),
        ),
    ]
