# Generated by Django 5.2.11 on 2026-02-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_post_full_description_en_post_full_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='post',
            name='full_description_uz',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_description_uz',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
    ]
