# Generated by Django 5.2.11 on 2026-02-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='', verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=models.TextField(default='', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_uz',
            field=models.TextField(default='', null=True, verbose_name='Краткое описание'),
        ),
    ]
